### ISSUE TITLE
Crash ao clicar no teclado após preencher última coluna

### ISSUE THREAD

**Issue by flyinggdragon** [gairin/TermoClone#1]
Descrição no console:

vendor.js:28080 ERROR TypeError: Cannot set properties of undefined (setting '0')
    at BoardComponent.charHandle (main.js:165:56)
    at KeyboardComponent.charInput (main.js:389:25)
    at HTMLTableCellElement.<anonymous> (main.js:370:16)
    at _ZoneDelegate.invokeTask (polyfills.js:7602:171)
    at vendor.js:43201:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (vendor.js:43201:30)
    at _ZoneDelegate.invokeTask (polyfills.js:7602:54)
    at Object.onInvokeTask (vendor.js:43503:25)
    at _ZoneDelegate.invokeTask (polyfills.js:7602:54)
    at Zone.runTask (polyfills.js:7404:37)

**Comment by gairin** [comment]
Arrumado.

Só foi necessário interromper o `charInput()`, `confirmAttempt()`, `backspace()` com um return caso o jogo já esteja terminado `this.ended == true` (gameService). Esta funcionalidade do estado do jogo foi adicionada nesta última atualização.

**Comment by gairin** [comment]
Arrumado.

Só foi necessário interromper o charInput(), confirmAttempt(), backspace() com um return caso o jogo já esteja terminado this.ended == true (gameService). Esta funcionalidade do estado do jogo foi adicionada nesta última atualização.

**Comment by gairin** [comment]
Arrumado.

Só foi necessário interromper o `charInput()`, `confirmAttempt()`, `backspace()` com um return caso o jogo já esteja terminado (`this.ended == true` no gameService). Esta funcionalidade do estado do jogo foi adicionada nesta última atualização.
